tasks:
  - name: appdev-week3-graphql
    before: |
      cd /workspace/netflix-example-schema
      nvm install node
      npm install -g npm@latest
      npm install -g netlify-cli
      npm install
    command: |
      git remote -v | grep synedra && exit
      echo "workshop-astra-NETFLIX gitpod ready - LET'S DO THIS!"
      gp open README.md
ports:
  - port: 8888
    onOpen: open-preview
  - port: 3000
    onOpen: ignore      
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false
